config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  #get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'  
  resources :tasks 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :labels, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  before_validation{ email.downcase! }
  has_many :tasks, dependent: :destroy
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  after_destroy :ensure_an_admin_remains
  after_update :ensure_an_admin_remains
  
  private

  def ensure_an_admin_remains
    if User.where(admin: "true").count.zero?
      raise "最後の管理者は削除できません！"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  PER = 3
  def index
  @users = User.includes(:tasks)
  end
  
  def show 
    @tasks = Task.includes(:user).where(user_id: params[:id]).page(page_display).per(PER)
  end
  
  def new
    @user = User.new 
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path(@user), notice: "「#{@user.name}」を登録しました。"
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    begin
      @user.update(user_params)
      redirect_to admin_users_path, notice: "「#{@user.name}」を更新しまいした。" 
    rescue Exception => e
      redirect_to admin_users_path,notice: "「#{e.message}」"
    end
  end 

  def destroy
    @user = User.find(params[:id])
      begin
        @user.destroy
        redirect_to admin_users_path, notice: "「#{@user.name}」を削除しました。" 
      rescue Exception => e
        redirect_to admin_users_path,notice: "「#{e.message}」"
      end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    raise Forbidden unless current_user.admin?
  end

  def page_display
    params[:page]
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_correct_user, only: [:show]
  before_action :logged_in, only: [:new]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      redirect_to tasks_path
    end
  end
  
  def logged_in
    if logged_in?
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>管理者登録</h1>
<p id = "notice"><%= notice %></p>
<div class = "admin_submit">
  <%= form_with(model:[:admin, @user], local: true) do |f| %>
    <%= f.hidden_field :created_at %>
    <%= f.hidden_field :uodated_at %>
    <%= f.label :name %>
    <%= f.text_field :name , class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'%>
    <%= f.label :管理者権限, class: 'form-check-label' %>
    <%= f.check_box :admin, class: 'form-check-input' %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password ,class: 'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation , class: 'form-control' %>
    <p><%= f.submit "登録する", class: 'btn btn-default' %></p>
  <% end %>
  <%= link_to '一覧', admin_users_path ,class: "nav-link"%>
</div>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>
<p id = "notice"><%= notice %></p>
<%= link_to 'ユーザー登録', new_admin_user_path ,class: "btn btn-default "%>
<%= link_to 'ラベル作成', new_label_path ,class: "btn btn-default "%>
<table class = "table table-hover admin">
  <tr>
    <th><%= t("activerecord.models.user") %></th>
    <th><%= t("activerecord.models.email") %></th>
    <th><%= t("activerecord.models.admin") %></th>
    <th><%= t("activerecord.models.created_at") %></th>
    <th><%= t("activerecord.models.updated_at") %></th>
    <th><%= t("activerecord.models.tasks") %></th>
    <th><%= t("activerecord.models.edit") %></th>
    <th><%= t("activerecord.models.delete") %></th>

  </tr>
    <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, [:admin, user] %></td>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>
    <td><%= user.created_at.to_s(:published_on) %></td>
    <td><%= user.updated_at.to_s(:published_on) %></td>
    <td><%= user.tasks.size %></td>
    <td><%= link_to '編集', edit_admin_user_path(user), class: "btn btn-primary mr-3" %></td>
    <td><%= link_to '削除', [:admin, user],method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: "btn btn-danger" %>
  </tr>
    <% end %>
</table>

app/views/admin/users/new.html.erb
<h1>管理者登録</h1>
<div class = "admin_submit">
  <%= form_with(model:[:admin, @user], local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name , class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'%>
    <%= f.label :管理者権限, class: 'form-check-label' %>
    <%= f.check_box :admin, class: 'form-check-input' %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password ,class: 'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation , class: 'form-control' %>
    <p><%= f.submit "登録する", class: 'btn btn-default' %></p>
  <% end %>
  <%= link_to '一覧', admin_users_path ,class: "nav-link"%>
</div>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>
<%= link_to 'ユーザー登録', new_admin_user_path ,class: "btn btn-default "%>
<table class = "table table-hover">
  <tr>
    <th><%= t("activerecord.models.created_at")  %></th>
    <th><%= t("activerecord.models.priority") %></th>
    <th><%= t("activerecord.models.title") %></th>
    <th><%= t("activerecord.models.content") %></th>
    <th><%= t("activerecord.models.deadline") %></th>
    <th><%= t("activerecord.models.status") %></th>
  </tr>
  <% @tasks.each do |task| %>
    <br>
    <tr>
    <td class="task-item_createdAt" ><%= task.created_at.to_s(:published_on) %></td>
    <td><%= task.priority %></td>
    <td class="task-item__title" >
      <%= task.title %>
    </td>
    <td class="task-item__content"><%= task.content %></td>
    <td><%= task.deadline %></td>
    <td><%= task.status%></td>
    </tr>
    <% end %>
</table>
  <br>
  <%= paginate @tasks %>