config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  #get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'  
  resources :tasks 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :labels, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskTheTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <div class="container">  
        <h4>AskTheTask</h4>
      <% if logged_in? %>
        <%= link_to "My page", user_path(current_user.id), class: 'btn btn-default prof'%>
        <%= link_to "Logout", session_path(current_user.id), method: :delete, class: 'btn btn-default prof' %>
      <% else %>
        <%= link_to "Sign up", new_user_path, class: 'btn btn-default prof' %>
        <%= link_to "Login", new_session_path, class: 'btn btn-default prof'%>
      <% end %>
      <% if logged_in? && current_user.admin? %>
        <%= link_to "管理画面", admin_users_path, class: 'btn btn-default prof'%>
      <% end %>
    </div>
  </header>
  <body>
    <%= yield %>
  </body>
</html>